# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install and Build 🔧 and Deploy
        run: |
          cp .env.production .env
          bun i
          bun add -g netlify-cli
          netlify build
          netlify deploy --prod --dir=.netlify --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEEPL_AUTH_KEY: ${{ secrets.DEEPL_AUTH_KEY }}
